### PR TITLE
Fix btoa context error

### LINKED ISSUE #196: btoa is undefined depending on the call context
I work w/ TypeScript and angular framework. When I call for exemple `repo.write(...)` from a service method, `atob` is null whereas `window.atob` works well.

### PR DESCRIPTION
**Pull request by firehist**
It resolves #196 . Just ensure that var `atob` in Github context coming from `window.atob`

### CODE REVIEW

**Comment by aendrew** [comment]
Closing until passes tests and I can be convinced this is actually necessary. Please comment to reopen.

**Comment by firehist** [comment]
Yes sorry, im so slow :p
I should never do as many things at the time.

**Comment by aendrew** [comment]
@firehist No worries! Definitely know how that goes. :smile: 

Let me know once the tests are passing again and I'll take another look at it!

**Comment by firehist** [comment]
Thanks a lot ;)
I'll.

**Comment by firehist** [comment]
@aendrew Tests pass locally, we can reopen PR.

**Comment by aendrew** [comment]
@firehist Cool! Mind pushing your changes so Travis can run the tests? Thanks!

**Comment by firehist** [comment]
=> https://travis-ci.org/michael/github/builds/68023787

**Comment by aendrew** [comment]
@firehist Cool! LGTM — mind squashing your commits? Thanks! :+1:

**Comment by firehist** [comment]
I squashed my commits to remove my "trigger-commit" Github PR update :)

**Comment by aendrew** [comment]
Apols for the delay! Merging! Thanks for the PR! :+1: :shipit:

**Comment by firehist** [comment]
No problem, results is merged :smile:

**Comment by adjohnson916** [comment]
+1 will this be released to bower?

**Comment by aendrew** [comment]
@adjohnson916 I need to do a new release. For now, just do `bower install github#master --save`.

**Pull request merged**
