### PR TITLE
Support Chinese file name

### PR DESCRIPTION
**Pull request by ele828**
As a Chinese, I can't upload a file with Chinese File name. Or maybe some other languages besides English.

Here, I encode the URI to be uploaded to make it works well.

thanks :)

### CODE REVIEW

**Comment by aendrew** [comment]
Hi! Thanks for your contribution!

Seems all the tests are passing, and the issue is more due to how I'm adding btoa in NodeJS. 

That said, could you please contribute some unit tests and rebase? Thanks!

**Comment by ele828** [comment]
Of course, but unfortunately, I can't run the source code. After I run ``npm install``, all the test cases in test folder goes wrong, which is caused by ``btoa is not defined``. :(...

**Comment by aendrew** [comment]
@ele828 That's been fixed in the last commit I've just pushed. Pull from `master` please!

**Comment by ele828** [comment]
@aendrew It's done, works well :)

**Comment by aendrew** [comment]
Cool! Thanks for your contribution!

**Pull request merged**
