### PR TITLE
Get contributors list with additions, deletions, and commit counts

### PR DESCRIPTION
**Pull request by eugef**
Adding support for this API call https://developer.github.com/v3/repos/statistics/#code-frequency

### CODE REVIEW

**Comment by eugef** [comment]
Tests for "Repo Deleted" failed but this is not concern of this PR

**Comment by aendrew** [comment]
Howdy! I restarted the build and the tests check out. Must be a race condition or something with the repo deleted test, will have to investigate.

At any rate, have tested and reviewed and LGTM; please add documentation to README.md and rebase, will then merge.

Thanks for your work!

**Comment by eugef** [comment]
Hi @aendrew, sorry for delay.

I've added the documentation and rebased my PR.

**Comment by aendrew** [comment]
@eugef No worries for the delay! Thanks for doing that! Merging now! :boom: :+1: :shipit:

**Pull request merged**
