### PR TITLE
Add the make release function

### PR DESCRIPTION
**Pull request by alexcanessa**
Create a make release function, which allows to create a release from a tag with given options.

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
Hi @alexcanessa. Thank you for your contribution!

Before we can merge your PR, can you include some tests and update the README file to document your method? Also, are all the options you mention mandatory? It might be worth to specify that as well.

**Comment by AurelioDeRosa** [comment]
Hi @alexcanessa. Did you have the chance to update this PR? I'd love to merge it.

**Comment by AurelioDeRosa** [comment]
I've also found that this PR is a subset of https://github.com/michael/github/pull/162. However the other PR is very old, so if you can update yours to include all the methods while proving tests and documentation, we can keep this one.

**Comment by clayreimann** [comment]
This feature is already in the library. http://michael.github.io/github/docs/1.1.0/Repository.html#createRelease

**Pull request closed without merging**
