### PR TITLE
Implements Search API

### PR DESCRIPTION
**Pull request by cassioscabral**
Implements basic Search API and added examples to README.md explaining how to use it.

### CODE REVIEW

**Comment by yannickoo** [comment]
I think @aendrew would say needs tests :)

**Comment by aendrew** [comment]
Yep, what @yannickoo said. LGTM otherwise, though! :+1:

**Comment by cassioscabral** [comment]
I've added the tests for the search API and squashed the commits. Didn't knew about the squash, thanks for the warning.

**Comment by aendrew** [comment]
Just merged this; fantastic work @cassioscabral! Many thanks! :tada: :shipit: :+1:

**Comment by cassioscabral** [comment]
Thank you @aendrew

**Pull request closed without merging**
