### PR TITLE
Use `_requestAllPages` for search endpoints

### PR DESCRIPTION
**Pull request by chrisronline**
This PR changes the all search endpoints to use `_requestAllPages` instead of `_request` to support getting the full set of results. 

My concern is how the flattening process should work - the result set is an array of responses instead of a single response. However, my change does not break tests since it seems the tests do not care about the nature of the response object.

How do you recommend I proceed with this?

Thanks

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
Hi.

Thank you for the PR. This is a good change and because it might break quite a few things, I'd rather have it for version 1.0. Any thoughts @clayreimann @aendrew?

**Comment by clayreimann** [comment]
@AurelioDeRosa I don't think this is liable to break code, but if you'd rather hold off then that's fine.

I also think that in general PRs should not bump the package version.

**Comment by chrisronline** [comment]
Removed the package version and changelog additions

**Comment by clayreimann** [comment]
@chrisronline This was just released in v1.2.0

**Pull request closed without merging**
