### PR TITLE
Add type, sort, per_page, and page options to User.repos call

### PR DESCRIPTION
**Pull request by mikec**
I needed the ability to set these

### CODE REVIEW

**Comment by aendrew** [comment]
Hi @mikec!

Could you please add a unit test for these options? Will happily merge after. Thanks!

**Comment by mikec** [comment]
@aendrew paging wasn't working so I updated `user.repos` to get a single page instead of all pages. I think the same should be applied to `user.userRepos` and `user.orgRepos`

**Comment by aendrew** [comment]
@mikec Quite agreed re: `user.userRepos` and `user.orgRepos`, nice implementation. I'll merge this now, could you do userRepos and orgRepos as a separate PR? Thanks!

**Comment by mikec** [comment]
@aendrew :+1:

**Comment by aendrew** [comment]
Merged! Thanks for your excellent contribution! :+1: :shipit:  :tada:

**Pull request closed without merging**
