### PR TITLE
Add options for getting list pull requests

### PR DESCRIPTION
**Pull request by sairoutine**
I want to get list of pull requests with options of `sort`, `direction` and so on.
But currently, I can specify only `state` option.
So I've added specifying some options to getting list pull requests.

https://developer.github.com/v3/pulls/#list-pull-requests

### CODE REVIEW

**Comment by sairoutine** [comment]
I expect that https://github.com/michael/github/pull/249 commit causes repo.getSha failed to pass test.

**Comment by aendrew** [comment]
@sairoutine c3d5bb6fdd7cb330d808b69b80278d890e0c34bc doesn't touch anything testing or code-related. It's likely your commit broke something.

Regardless, you'll need to add unit tests before I can merge this. We're hoping to merge #248 in the next day or two; if you could rebase against that and write your tests in Chai, that'd be great. 

Thanks!

**Comment by sairoutine** [comment]
All right.
I’m looking forward to your merging https://github.com/michael/github/pull/248 !

Thanks.

**Comment by aendrew** [comment]
@sairoutine Hi! I've merged #248! :tada:

**Comment by sairoutine** [comment]
I had written the test code, and succeeded to pass the test in my local PC.
But, on Travis CI, my code did not pass the test.
I want some helps.

Thanks.

**Comment by aendrew** [comment]
Hi @sairoutine!

I just checked out your PR and ran the tests, worked fine for me. Travis might just be acting :hankey: right now. 

Closed via 3eff47eb9057a5af75a941fd19ea94b5485f0000.

**Pull request closed without merging**
