### PR TITLE
Rate Limit

### PR DESCRIPTION
**Pull request by websemantics**
Get your current rate limit status

### CODE REVIEW

**Comment by aendrew** [comment]
Cool. Please add documentation to README.md and rebase. Thanks!

**Comment by aendrew** [comment]
Also, please add a test! Thanks!

**Comment by websemantics** [comment]
apologies for never responding, this was outside of my radar completely ...

**Comment by aendrew** [comment]
Hi!
Erm, apologies, I totally don't remember closing this PR. Reopening.

**Comment by AurelioDeRosa** [comment]
@websemantics Can you please add a test for this PR and also rebase?

**Comment by websemantics** [comment]
@AurelioDeRosa will do ..

**Comment by AurelioDeRosa** [comment]
Thank you

**Comment by AurelioDeRosa** [comment]
The API has been added with commit 045d8b7dfe2d440387a3cfa2c6b493282e7e6191.

**Pull request closed without merging**
