### PR TITLE
Add data arg to repo.remove callback

### PR DESCRIPTION
**Pull request by timwis**
This is passed things like the commit url

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
Hi.

Thank you for your PR. Could you improve the relevant test to address this change?

**Comment by clayreimann** [comment]
No code here. Open a new PR when you have changes to contribute.

**Comment by timwis** [comment]
Hey @clayreimann, I've given you the benefit of the doubt but I just wanted to let you know that your comment came across as a bit rude the way it was worded. Assuming you didn't intend for that, I'd encourage you to re-read it and hopefully you'll see what I mean. I try to make a practice of submitting pull requests whenever I see an issue in documentation (not just code). I understand that you'd like a test written as well as the documentation update, but that doesn't make the documentation update any less accurate. My pull request simply documents an argument that is _already_ present in the code, just not documented (despite it being documented in other, similar methods). When I see comments worded like that, I feel discouraged from contributing in the future, and I'm sure that's not what you intended.

**Comment by clayreimann** [comment]
@timwis you're right, my comment was a bit abrupt. I guess I assumed from the comment about a test that there was at one point actual code in the branch that you'd force-pushed out.

I do appreciate your efforts to improve the documentation though! At this point the code is mostly self-documenting and the [documentation is published](https://michael.github.io/github/docs/1.2.1/index.html) to [the website](https://michael.github.io/github/).

If I haven't put you off of contributing in the future we could really use better examples of doing real things  with the library to help people see what's possible.

Again, my apologies for sounding so rude.

**Comment by timwis** [comment]
No worries @clayreimann - thanks!

**Pull request closed without merging**
