### PR TITLE
Add getStatuses repo endpoint

### PR DESCRIPTION
**Pull request by pik**
Adds the Repo endpoint for `https://api.github.com/repos/<user>/<repo>/statuses/<sha>`

edit: Build is failing but this seems unrelated - 

```
npm ERR! phantomjs2@2.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs2@2.0.0 install script 'node install.js'.```

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
Hi @pik and thank you for your PR. Can you please add a test for your method and also update the README to document it?

**Comment by pik** [comment]
Updated tests and readme - also I switched to getStatuses from listStatuses since that seems more consistent with the endpoint taking a single sha for an argument.

**Comment by AurelioDeRosa** [comment]
Thank you for the update. I'm going to merge this PR.

**Comment by AurelioDeRosa** [comment]
Merged with a minor update. Thank you for contributing.

**Pull request closed without merging**
