### PR TITLE
repo: add getRepo with fullname

### PR DESCRIPTION
**Pull request by yorkie**
Hooks API has direct full_name to be respond, so adding a way to
initistant the repo object with full_name should be more convinent.

Now we are able to get a repo:

```js
githubapi.getRepo('nodejs/node')
```

Thanks

### CODE REVIEW

**Comment by EliCDavis** [comment]
:+1: , would have helped a lot on my project earlier :sweat_smile:

**Comment by yorkie** [comment]
Hey @EliCDavis if you hope directly apply my changes into your project, you are able to use https://github.com/weflex/octop for now, because I found the repo under DevelopmentSeed still not active and with so many PR and issues without any feedback. Because I will be working on Github API, so I think Octop might be more active during this time, BTW, of course hope this would be merged as well :-)

**Comment by aendrew** [comment]
This looks like a great commit. Thanks for adding unit tests! Merging for 0.10.7!

**Comment by yorkie** [comment]
:-)

**Pull request merged**
