### PR TITLE
Create comment on issue function

### PR DESCRIPTION
**Pull request by randalmaia**
Create comment on issue function

thanks for this api.

### CODE REVIEW

**Comment by fdaciuk** [comment]
Nice feature :) 

+1

**Comment by aendrew** [comment]
Hi!
Thanks for the PR! Looks like a good feature and thanks ever-so-much for writing a test spec for the Issues API!

Could you please squash your commits? I'll then merge it thereafter. Thanks! :+1: :shipit:

**Comment by randalmaia** [comment]
Why squash the commits @aendrew ? I dont understand

**Comment by aendrew** [comment]
@randalmaia Generally open source projects ask you to either rebase against master or squash your commits. This is to prevent a lot of iterative commits from filling up the project's commit history. 

I've done so for you and merged to master. Thanks for your contribution! :+1: :shipit:

**Pull request closed without merging**
