### PR TITLE
Fetch all issues, not just the first 30.

### PR DESCRIPTION
**Pull request by torgeir**
I'm guessing this should be applied for other calls that make use of paging as well?

### CODE REVIEW

**Comment by revolunet** [comment]
works great, rebase please :)

**Comment by aendrew** [comment]
@revolunet Thanks! Marking as RTBC. 

@torgeir Please fix the conflicts and I'll test/merge this PR. Thanks for your work!

**Comment by torgeir** [comment]
Rebased! I'm not able to verify it still works atm, let me know if it doesn't work out.

**Comment by aendrew** [comment]
Verifying it works, merging now. Thanks for your contribution!

**Pull request merged**
