### PR TITLE
Adds bower.json

### PR DESCRIPTION
**Pull request by aendrew**
Would be nice to be able to manage this via Bower. You'll want to add it to the directory via [`bower register`](http://bower.io/docs/creating-packages/#register).

### CODE REVIEW

**Comment by eugef** [comment]
+1 for Bower support

**Comment by mateusfreira** [comment]
+1 for Bower support

**Comment by andrewmcwatters** [comment]
:+1:

**Comment by onmyway133** [comment]
It is OK but I can't find it in http://bower.io/search/?q=github

**Comment by clayreimann** [comment]
Bower support was deprecated because dist files don't belong in git. You can install the npm package for the built files, or you can use npmcdn if you don't want to host the files yourself.

**Pull request merged**
