### PR TITLE
allow options to override the github url for usage with github enterprise

### PR DESCRIPTION
**Pull request by afex**

### CODE REVIEW

**Comment by aendrew** [comment]
Duplicate of #150. First to add documentation will get the merge.

**Comment by kpdecker** [comment]
This change could potentially have unintended side effects due to the shared `API_URL` variable. If multiple `Github` objects are instantiated, then the server used by all instances will change to whatever is passed to the last call made.

**Comment by aendrew** [comment]
Ah, indeed, @kpdecker is correct. The `API_URL` variable should be defined inside of the constructor.

**Comment by aendrew** [comment]
#150 has been merged, closing this.

**Pull request closed without merging**
