### PR TITLE
Make Github.Issue.list options matter

### PR DESCRIPTION
**Pull request by fiddur**
Issue.list takes options.  With this patch, you can use these options to filter the issues wanted, e.g.          
issues.list({"labels":"bug,ui"}, callback)

Before this patch, the options were sent as stringified data in the GET-request…

### CODE REVIEW

**Comment by gajjargaurav** [comment]
I wanted closed issues (e.g. issues.list({state:"closed"}, cb)) and ended up with similar solution so I'd like PR merged up quickly

**Comment by aendrew** [comment]
I'll take a look at this next chance I get.

**Comment by gajjargaurav** [comment]
Thanks @aendrew, looking forward to that

**Comment by aendrew** [comment]
LGTM. Merging! :+1: :shipit: Thanks for your efforts, @fiddur!

**Pull request merged**
