### PR TITLE
Added create function so you can create issues

### PR DESCRIPTION
**Pull request by pcanella**
I feel like we should flesh this out a bit more by adding Issue creation and eventually issue comment creation.

### CODE REVIEW

**Comment by aendrew** [comment]
@pcanella Cool! Mind adding a unit test? Thanks!

**Comment by aendrew** [comment]
Closed in error; reopening.

**Comment by pcanella** [comment]
Ah yes, I'm sorry! Will add one when I have a minute

**Comment by AurelioDeRosa** [comment]
Hi @pcanella. Did you have a chance to update your PR? I'd like to merge it.

**Comment by AurelioDeRosa** [comment]
Closing this PR in favor of #291.

**Pull request closed without merging**
